name: Entry
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    outputs:
      enable: ${{ steps.ok-to-test.outputs.enable }}
    steps:
      - name: echo to file
        run: |
          echo 123 > test.txt
          ls
          cat test.txt