name: CI 5
on:
  workflow_run:
    workflows: ["Entry-x"]
    types: ["completed"]
jobs:
  ci-1-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo to file
        run: |
          echo "hello ci-5 workflow" > test.txt
          ls
          cat test.txt