name: Echo TEST
on:
  push:
    branches:
      - main
      - "**"
jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - name: echo to file
        run: |
          echo 123 > test.txt
          ls
          cat test.txt