name: Entry
on:
  push:
    branches:
      - test-workflow-run-property
  pull_request:
    branches:
      - '**'
jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: echo to file
        run: |
          echo test success