name: Entry
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: echo to file
        run: |
          echo test failed
          abcdddddddd