name: Release (Testing)
on:
  release:
    types: [ created ]
jobs:
  release-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compress File
        run: |
          tar -cvf aa.tar.gz a
          tar -cvf dd.tar.gz ./d1
          mkdir d2
          mv ./dd.tar.gz ./d2
      - name: Upload File
        uses: jasonetco/upload-to-release@v0.1.1
        with:
          args: aa.tar.gz application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload File With Dir
        uses: jasonetco/upload-to-release@v0.1.1
        with:
          args: ./d2/dd.tar.gz applicaiton/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Rename File
        run: |
          touch hello.txt
          mv hello{,_$GITHUB_REF_NAME}.txt
      - name: Upload File
        uses: jasonetco/upload-to-release@v0.1.1
        with:
          args: ./hello_$GITHUB_REF_NAME.txt text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
