name: Release (Testing)
on:
  release:
    types: [ created ]
jobs:
  release-test:
    runs-on: ubuntu-latest
    steps:
      - name: Upload File
        uses: jasonetco/upload-to-release@v0.1.1
        with:
          args: a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          