name: Release (Testing)
on:
  release:
    type: [ created ]
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Located At
        run: |
          echo "::dir is $(pwd)::"
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Testing Python
        run: python --version
      - name: Compress File
        run: |
          tar -czf aa.tar.gz ./a
          ls -al
      - name: Decompress File
        run: |
          mkdir ./sdk
          tar -xzf aa.tar.gz -C sdk
          tree