name: Tips (Test)
on:
  push:
    branches:
      - main

jobs:
  tips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd ./d1
          pwd
      - run: pwd