on:
  workflow_run:
    workflows: [ "Echo TEST","Tag Push" ]
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
      - run: java -version